export const ADD_SERVICE = 'ADD_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const SELECT_UPDATE_SERVICE = 'SELECT_UPDATE_SERVICE';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const INVALIDATE_SERVICE_FIELD = 'INVALIDATE_SERVICE_FIELD';
export const RESET_SERVICE_FORM = 'RESET_SERVICE_FORM';
